### ISSUE TITLE
安装出错

### ISSUE THREAD

**Issue by HeroBarry** [tumobi/nideshop-admin#3]
错误信息如下：
> fsevents@1.1.2 install C:\Users\Tiger\Desktop\nideshop\nideshop-admin\node_modules\fsevents
> node install

> fcopy-pre-bundled@0.3.4 install C:\Users\Tiger\Desktop\nideshop\nideshop-admin\node_modules\fcopy-pre-bundled
> echo ''

''

> electron@1.7.5 postinstall C:\Users\Tiger\Desktop\nideshop\nideshop-admin\node_modules\electron
> node install.js

C:\Users\Tiger\Desktop\nideshop\nideshop-admin\node_modules\electron\install.js:48
  throw err
  ^

Error: connect ETIMEDOUT 54.231.40.11:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:14)
npm WARN nideshop-admin@0.0.0 No repository field.
npm WARN nideshop-admin@0.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.7.5 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.7.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Tiger\AppData\Roaming\npm-cache\_logs\2017-09-22T13_24_54_757Z-debug.log

node使用经验不足，不知道如何解决，跪请大神帮忙看看

**Comment by HeroBarry** [comment]
Windows 环境

**Comment by PikachuWu** [comment]
ETIMEDOUT 54.231.40.11:443   你可以使用cnpm 代替npm 不然就得翻 墙

**Comment by HeroBarry** [comment]
@PikachuWu 完美解决  感谢
