### ISSUE TITLE
macos下npm install提示：Unsupported platform for 7zip-bin-win@2.1.1: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})

### ISSUE THREAD

**Issue by wzlee** [tumobi/nideshop-admin#5]
![image](https://user-images.githubusercontent.com/4182865/31051825-49a06d7c-a638-11e7-9b56-24fada6da77a.png)

**Comment by baitongda** [comment]
我的也一样

**Comment by ZLJASON** [comment]
我也一样

**Comment by ZLJASON** [comment]
npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN nideshop-admin@0.0.0 No repository field.
npm WARN nideshop-admin@0.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.1.0 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.1.0: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@1.1.0 (node_modules/7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.1.0: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
